import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
export default function Home(props) {
 

  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {
          props.hello.map((res) => {
            return <div key={res.id}  onClick={()=>router.push(`${res.id}`)} >{res.name}</div>
          })
        }
      </div>

    </div>
  )
}


export async function getStaticProps(context) {
  const { data } = await axios.get("https://jsonplaceholder.typicode.com/users")

  return {
    props: {
      hello: data
    }, // will be passed to the page component as props
  }
}